language: python
python:
- '3.6'
- '3.5'
- '3.4'
- '2.7'
- '3.5-dev'
- '3.6-dev'
- '3.7-dev'
- 'pypy'
- 'pypy3'
- 'pypy-5.3.1'
install:
- pip install -r requirements.txt
- python setup.py install
script:
- python -m unittest discover
deploy:
  provider: pypi
  user: pusnow
  password:
    secure: Vi4OSVJhsf7UHBD7Sazc7lL/GW9qCq8FR6MQBZ9sGtZWilIZZH2+/Kr011xyQe55V+e606e6XR0dSZB5E8m31AVSSJDvW9oY+2RbyL/7MIn/QyEwVM6L2oYcAqe/bL2cTBv2eu+M0KJn/G5X2QW61VFz0YhTBdXHdeRbZ5zhruUXsrQxZ3PJI/kFiF0EfAhFruv6CdEjFNUWDtlHuTbH17/jM/07OtN0hP/6qdR/CpHxwT08IZLR9OwDxCb7gInr3HXsxfwN5QCQpkse+VUgbifB3jSmyMV4jK8ZkBebB2yOsHMT4xOiS3j2PcA/eegaKE/vl/5gRx3kwVJ2VxCc8lrnsrk+rffZGM8vsIZbPHsh932ud3yzrvQEUgJyB07PKYk9SZw/oWnL574xPD3G5qmJJmkntUCIbW/ra2YR7Et+HcT+B8JfouduAwRP7K/OuLSSLg+yPZyPjpfi2VmnNWYXU4CD4DjKyYzhNj5xUrI0NPIAZApciShoPTYoEb2w9CLLH3ClYH+cIp4GGxYw8Y+bVSh7gjsvDuZ9JOoHVehvwvp4YWSm/wTgHijWl19iuyQSxOIgHNdyA4lhHK+JVGyasUQRaMZkrbxr6klvxcxk+GhpEZEbAansvoe/Z0/cXxQ8Ws6SopYLrgbcUBQT+4O202tCtVKJBQDN4nl046s=
  on:
    distributions: sdist bdist_wheel
    repo: Pusnow/KS-X-1026-Python
